version: "3.8"

services:
  php-fpm:
    build: docker/php
    volumes:
      - ./backend:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=docker-test-project"
    networks:
      - symfony
    depends_on:
      - db

  nginx:
    build: docker/nginx
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony

  db:
    build: docker/postgresql
    command: -c 'log_min_messages=debug5'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    networks:
      - symfony
    ports:
      - "5432:5432"

volumes:
  db:
  composer:

networks:
  symfony: